version: '3.8'

services:
  app:
    build: .
    container_name: apppcr_php
    ports:
      - "8084:80"
      - "4444:443"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: apppcr_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: apppcr
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d  # <- 🔥 Carga SQL inicial automática
    ports:
      - "3310:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: apppcr_phpmyadmin
    ports:
      - "8087:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass

